version: "3.7"
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    ports: 
      - "8000"
    volumes:
      - .:/usr/src/app
    networks:
      - backend
    links:
       - mongo
  mongo:
    image: mongo
    restart: always
    ports: 
      - "27777:27017"
    networks:
      - backend
    volumes:
      - 'mongo:/data/configdb'

volumes:
  mongo:

networks:
  backend:
        

